# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
estep_lmm_cpp <- function(res_fixed, Z, group_indicator, inv_Omega, sigma2, J) {
    .Call(`_mixedelnet_estep_lmm_cpp`, res_fixed, Z, group_indicator, inv_Omega, sigma2, J)
}

#' @export
log_lik_lmm_cpp <- function(y, Z, X, group_indicator, beta, Omega, sigma2, J) {
    .Call(`_mixedelnet_log_lik_lmm_cpp`, y, Z, X, group_indicator, beta, Omega, sigma2, J)
}

